title: "Prashant Kanuru Blogs"
description: "My machine learning notes and blogs"
baseurl: "/prashant-kanuru-blogs" # your repository name
url: "https://prashantkanuru.github.io" # your github pages root domain

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  math_engine: mathjax

theme: null
plugins: []